### ISSUE TITLE
Issue with interpretation of indents in lca.py

### ISSUE THREAD

**Issue by morien** [naturalis/galaxy-tool-lca#1]
I was able to reproduce this issue in both CentOS(v8) and MacOS(v10.15.2) environments:
```
  File "~/programs/galaxy-tool-lca/lca.py", line 38
    filterHitsParam = filterParam.strip()
                                        ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by gbbio** [comment]
Thanks for this comment. It looks like that somehow the comments in the script are indented with four spaces instead of tabs.

**Comment by gbbio** [comment]
#d3dac06
